# Generated by Django 2.2.9 on 2020-02-24 10:43

from django.db import migrations, models
import django.db.models.deletion
import wagtailtrans.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0010_translatablepageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatablepageitem',
            name='language',
            field=models.ForeignKey(default=wagtailtrans.models._language_default, on_delete=django.db.models.deletion.CASCADE, related_name='translatable_page_items', to='wagtailtrans.Language'),
        ),
        migrations.AlterField(
            model_name='translatablepageitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
